# Generated by Django 2.1.3 on 2018-11-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.CharField(max_length=250)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='sences',
            name='sence',
        ),
        migrations.DeleteModel(
            name='Sences',
        ),
    ]
