# Generated by Django 2.1.3 on 2018-11-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181127_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_purchased',
            field=models.DateTimeField(blank=True),
        ),
    ]
